config/routes.rb
Rails.application.routes.draw do
  
	resource :session
	resources :passwords, param: :token
	resources :entries

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

	get "up" => "rails/health#show", as: :rails_health_check
	
  # Defines the root path route ("/")
  root "entries#index"
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
	
	# Relationships
	has_many :entries
	
end

app/models/concerns/sluggable.rb
module Sluggable
	extend ActiveSupport::Concern
	
	included do
		before_create :build_slug
	end
	
	private
	
		def build_slug
			begin
				self.slug = SecureRandom.hex(6)
			end while self.class.exists?(:slug => slug)
		end
		
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/entry.rb
class Entry < ApplicationRecord
	
	# Pre-flight
	include Sluggable
	
	# Relationships
	belongs_to :site
	belongs_to :category
	
	# Activestorage
	has_one_attached :cover
	
	# Pretty URL's
	extend FriendlyId
	friendly_id :slug, use: :slugged
	
	# Scopes
	scope :published, -> { where(is_published: true) }
	scope :drafts, -> { where(is_published: false) }
	
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/site.rb
class Site < ApplicationRecord
	
	# Relationships
	has_many :entries
	
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	allow_unauthenticated_access only: [:index, :show]
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries or /entries.json
  def index
    @entries = Entry.published.order(created_at: :desc)
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
		@drafts = Entry.drafts.order(created_at: :desc)
  end

  # GET /entries/1/edit
  def edit
		@categories = Category.all
		@metadata = eval(@entry.metadata_raw)
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)
		page = MetaInspector.new(@entry.og_url)
		@entry.url = page.untracked_url || page.url
		@entry.title = page.best_title
		@entry.caption = page.best_description
		@entry.metadata_raw = page.to_hash
		@entry.site = Site.where(url: page.host).first_or_create(favicon: page.images.favicon)
		respond_to do |format|
			if @entry.save
				format.html { redirect_to edit_entry_path(@entry), notice: "entry was successfully created." }
				format.json { render :show, status: :created, location: @entry }
			else
				format.html { render :new, status: :unprocessable_entity }
				format.json { render json: @entry.errors, status: :unprocessable_entity }
			end
		end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
		@entry.is_published = true
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to new_entry_path, notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy!

    respond_to do |format|
      format.html { redirect_to entries_path, status: :see_other, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.friendly.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.expect(entry: [ :og_url, :title, :caption, :category_id, :props, :cover ])
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email: params[:email])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def icon(path)
		File.open("app/assets/icons/#{path}", "rb") do |file|
			raw file.read
		end
	end
	
	def working_url?(url)
		uri = URI.parse(url)
		uri.is_a?(URI::HTTP) && !uri.host.nil?
		rescue URI::InvalidURIError
		false
	end

end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>" class="card">
	<%= turbo_frame_tag :media, src: entry_path(entry), loading: :lazy, turbo_frame: "_top", class: "cover-container", style: "aspect-ratio: #{ entry.cover.metadata["width"].to_f / entry.cover.metadata["height"].to_f }" do %>
		<div class="cover-loading">
			Loading...
		</div>
	<% end %>
	<div class="stack col gap-12">
		<div class="stack col gap-4">
			<p style="text-overflow: ellipsis; overflow: hidden; white-space: nowrap;"><%= link_to entry.title, entry.url, target: "_blank" %></p>
			<p class="fg-secondary"><%= entry.caption %></p>
		</div>
		<div class="stack row gap-4 wrap-children">
			<% if working_url?(entry.site.favicon) %>
				<span class="flair default with-icon">
					<i class="favicon"><%= image_tag url_for(entry.site.favicon) %></i>
					<%= entry.site.url %>
				</span>
			<% else %>
				<span class="flair default"><%= entry.site.url %></span>
			<% end %>
			<span class="flair default"><%= entry.category.name %></span>
		</div>
	</div>
</div>

app/views/entries/edit.html.erb
<div class="stack col gap-16 padding-24 max-width-500">
	<%= form_with(model: @entry) do |form| %>
		<div class="stack col gap-12">
			<% if @entry.errors.any? %>
				<div style="color: red">
					<h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>
			
					<ul>
						<% @entry.errors.each do |error| %>
							<li><%= error.full_message %></li>
						<% end %>
					</ul>
				</div>
			<% end %>
			<div class="stack col gap-6">
				<%= form.label :cover, style: "display: block" %>
				<div class="stack col gap-12" data-controller="cover-upload">
					<%= form.file_field :cover, multiple: false, direct_upload: true, data: { cover_upload_target: "input", data_max_files: 1 } %>
				</div>
			</div>
			<div class="stack col gap-6">
				<%= form.label :url, style: "display: block" %>
				<%= form.text_field :url %>
			</div>
			<div class="stack col gap-6">
				<%= form.label :category, style: "display: block" %>
				<div class="stack row gap-6 wrap-children">
					<%= form.collection_radio_buttons(:category_id, Category.all, :id, :name, required: true) do |category| %>
						<div class="radio">
							<%= category.radio_button %>
							<%= category.label %>
						</div>
					<% end %>
				</div>	
			</div>
			<div class="stack col gap-6">
				<%= form.label :title, style: "display: block" %>
				<%= form.text_field :title %>
			</div>
			<div class="stack col gap-6">
				<%= form.label :caption, style: "display: block" %>
				<%= form.text_area :caption %>
			</div>
			<div>
				<%= form.submit "Publish", class: "btn primary" %>
			</div>
		</div>
	<% end %>
	<%= @metadata["images"] %>
	<% @metadata["images"].each do |image| %>
		<%= image_tag url_for(image) %>
	<% end %>
</div>

app/views/entries/index.html.erb
<% content_for :title, "logs.design" %>

<% if authenticated? %>
	<h1 class="site"><%= link_to "New entry", new_entry_path %>, <%= link_to "Sign out", session_path, data: { turbo_method: :delete } %></h1>
<% end %>

<div id="logs" data-controller="grid">
	<div class="card-sizer"></div>
	<% @entries.each do |entry| %>
		<%= render entry %>
	<% end %>
</div>

app/views/entries/new.html.erb
<div class="stack col gap-40">
	<div class="stack col gap-16 padding-24 max-width-500">
		<%= form_with(model: @entry) do |form| %>
			<div class="stack col gap-12">
				<% if @entry.errors.any? %>
					<div style="color: red">
						<h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>
				
						<ul>
							<% @entry.errors.each do |error| %>
								<li><%= error.full_message %></li>
							<% end %>
						</ul>
					</div>
				<% end %>
				<div class="stack col gap-6">
					<%= form.label :og_url, style: "display: block" %>
					<%= form.text_field :og_url, required: true %>
				</div>
				<div class="stack col gap-6">
					<%= form.label :category, style: "display: block" %>
					<div class="stack row gap-6 wrap-children">
						<%= form.collection_radio_buttons(:category_id, Category.all, :id, :name, required: true) do |category| %>
							<div class="radio">
								<%= category.radio_button %>
								<%= category.label %>
							</div>
						<% end %>
					</div>	
				</div>
				<div>
					<%= form.submit "Next", class: "btn primary" %>
				</div>
			</div>
		<% end %>
	</div>
	<div class="stack col gap-6 padding-24">
		<% @drafts.each do |draft| %>
			<p><%= link_to draft.title, edit_entry_path(draft) %> — <span class="fg-tertiary"><%= draft.category.name %>, <%= draft.site.url %></span></p>
		<% end %>
	</div>
</div>

app/views/entries/show.html.erb
<%= turbo_frame_tag :media, class: "cover-container", style: "aspect-ratio: #{ @entry.cover.metadata["width"].to_f / @entry.cover.metadata["height"].to_f }" do %>
	<% if @entry.cover.representable? %>
		<%= link_to @entry.url, target: "_blank", class: "cover" do %>
			<% if @entry.cover.video? %>
				<%= video_tag url_for(@entry.cover), controls: false, autoplay: true, muted: true, loop: true, playsinline: true %>
			<% elsif @entry.cover.image? %>
				<%= image_tag url_for(@entry.cover) %>
			<% end %>
		<% end %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Logs" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logs/edit.html.erb
<%= form_with(model: @log) do |form| %>
	<% if @log.errors.any? %>
		<div style="color: red">
			<h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

			<ul>
				<% @log.errors.each do |error| %>
					<li><%= error.full_message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<div>
		<%= form.label :cover, style: "display: block" %>
		<%= form.file_field :cover %>
	</div>

	<div>
		<%= form.label :url, style: "display: block" %>
		<%= form.text_field :url %>
	</div>
	
	<div>
		<%= form.label :category, style: "display: block" %>
		<%= form.collection_select(:category_id, Category.all, :id, :name, {:prompt => 'Pick a category'}, required: true) %>
	</div>

	<div>
		<%= form.label :title, style: "display: block" %>
		<%= form.text_field :title %>
	</div>

	<div>
		<%= form.label :caption, style: "display: block" %>
		<%= form.text_field :caption %>
	</div>

	<div>
		<%= form.submit %>
	</div>
<% end %>

app/views/logs/new.html.erb
<%= form_with(model: @log) do |form| %>
	<% if @log.errors.any? %>
		<div style="color: red">
			<h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

			<ul>
				<% @log.errors.each do |error| %>
					<li><%= error.full_message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div>
		<%= form.label :og_url, style: "display: block" %>
		<%= form.text_field :og_url %>
	</div>
	
	<div>
		<%= form.label :category, style: "display: block" %>
		<%= form.collection_select(:category_id, Category.all, :id, :name, {:prompt => 'Pick a category'}, required: true) %>
	</div>

	<div>
		<%= form.submit %>
	</div>
<% end %>